### ISSUE TITLE
Include no-bake energy balls

### ISSUE THREAD

**Issue by DanHickstein** [DanHickstein/recipes#1]

**Comment by DanHickstein** [comment]
Add these no-bake energy bites: 
![energy bites](https://user-images.githubusercontent.com/1107796/71626704-cacc2580-2bab-11ea-8997-1380ddf3ce7e.jpg)

**Comment by DanHickstein** [comment]
Here are some photos of the energy balls:

![balls3](https://user-images.githubusercontent.com/1107796/71627148-23042700-2bae-11ea-81d0-be9583743139.jpg)
![balls2](https://user-images.githubusercontent.com/1107796/71627150-23042700-2bae-11ea-8e19-d266f3b4ad42.jpg)
![balls1](https://user-images.githubusercontent.com/1107796/71627151-239cbd80-2bae-11ea-8eac-0810f13be6a0.jpg)

**Comment by laurajohnson** [comment]
These are cookies. They are soft.  They have chocolate. They are delicious.

**Comment by DanHickstein** [comment]
Included this recipe in the database: https://github.com/DanHickstein/recipes/blob/master/energy_balls.md

The only thing that I changed was to double the recipe (because why not?) and to decrease the honey from 1/3 to 1/4 cup (1/2 cup in the doubled recipe).
